database:
  name: ranked_choice_voting
  user: rcv_user
  password: your_mysql_password
  host: localhost
telegram:
  bot_token: YOUR_BOT_TOKEN
  webhook_host: YOUR_WEBHOOK_HOST
  webhook_port: YOUR_WEBHOOK_PORT
  webhook_url: YOUR_WEBHOOK_URL
  sudo_id: YOUR_SUDO_ID