settings:
  # whether bot is deployed in production mode
  production: True
  # auth bypass token for accessing webapp server
  # from when the website loaded directly on the browser
  auth_bypass_token: YOUR_AUTH_BYPASS_TOKEN
database:
  name: ranked_choice_voting
  user: rcv_user
  password: your_mysql_password
  host: localhost
telegram:
  bot_token: YOUR_BOT_TOKEN
  webhook_host: YOUR_WEBHOOK_HOST
  webhook_port: YOUR_WEBHOOK_PORT
  webhook_url: YOUR_WEBHOOK_URL
  sudo_id: YOUR_SUDO_ID